staging:
  domain:
    name: "nashvilleaacc.org@s188051.gridserver.com"
  deploy_to: "/home/188051/users/.home/domains/nashvilleaacc.org/html"
  repository: "git@github.com:ewillhite/naacc.git"
  branch: "master"

# production:
#   domain:
#     name: ""
#   deploy_to: ""
#   repository: ""
#   branch: "master"
